### ISSUE TITLE
Not working with controller

### ISSUE THREAD

**Issue by Vasantika20** [YeungKC/widgets_visibility_provider#1]
If i set ScrollController with ListView.builder() then its not working. I need to set controller for scroll to particular position in a list. Please help.

**Comment by YeungKC** [comment]
Thank you open new issue, I'll check it out and in the meantime maybe you can also provide the minimum reproducible code.

**Comment by Vasantika20** [comment]
Thank you for your quick response, i will wait for your next update.

**Comment by YeungKC** [comment]
I can't reproduce it, could you provide a minimum reproduction code?
