### ISSUE TITLE
Type casting issue with latest 3.0.0-nullsafety.0 

### ISSUE THREAD

**Issue by tw4452852** [YeungKC/widgets_visibility_provider#3]
Here's exception:

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
type 'WhereIterable<MapEntry<Key?, PositionData>?>' is not a subtype of type 'Iterable<MapEntry<Key,
PositionData>>' in type cast

When the exception was thrown, this was the stack:
#0      WidgetsVisibilityProviderBloc._schedulePositionUpdate.<anonymous closure> (package:widgets_visibility_provider/src/widgets_visibility_provider.dart:118:24)
#1      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#2      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#3      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#7      _invoke (dart:ui/hooks.dart:167:10)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#9      _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by YeungKC** [comment]
close
